from Tkinter import *
import random
import sqlite3
con=sqlite3.Connection('abc1')
cur=con.cursor()
root=Tk()
root.configure(bg='yellow')
Label(root,text='Welcome to RTO Database',font='times 20 bold',bg='light blue').pack()
Label(root,text='Project by :-',relief='ridge',font='times 10',bg='orange').pack(padx=10,pady=5)
Label(root,text='J.Anirudh Sharma',relief='raised',font='arial 15 bold',bg='orange').pack(padx=10,pady=5)
Label(root,text='Under the guidance of :-',relief='ridge',font='times 10',bg='orange').pack(padx=10,pady=5)
Label(root,text='Dr.Mahesh Kumar',relief='raised',font='arial 15 bold',bg='orange').pack(padx=10,pady=5)
def zz():
    q=Tk()
    q.configure(bg='black')
    Label(q,text='EnRoll no. :- 161B102',relief='raised',font='arial 15 bold',bg='orange').pack(padx=10,pady=5)
    Label(q,text='Contact info :',relief='raised',font='arial 25 bold',bg='orange').pack(padx=10,pady=5)
    Label(q,text='email : maxshotanirudh372@gmail.com',relief='raised',font='arial 15 bold',bg='orange').pack(padx=10,pady=5)
    Label(q,text='Mobile no. : 9984282828',relief='raised',font='arial 15 bold',bg='orange').pack(padx=10,pady=5)
    Label(q,text='Address : C13/147 Aurangabad Varanasi 221010',relief='raised',font='arial 15 bold',bg='orange').pack(padx=10,pady=5)
def zzz():
    q1=Tk()
    q1.configure(bg='light green')
    Label(q1,text='This project is inspired from day to day cars registraion and their information being fetched.',font='arial 15',bg='light green').pack(padx=10,pady=5)
    Label(q1,text='The main purpose is to solve the tedious way of searching information used by people.',font='arial 15',bg='light green').pack(padx=10,pady=5)
    Label(q1,text='By giving just a few keys we can get a load of data though this project.',font='arial 15',bg='light green').pack(padx=10,pady=5)
    Label(q1,text='I am thankful to my teacher Dr. Mahesh Kumar Sir for helping out in all of my errors.',font='arial 15',bg='light green').pack(padx=10,pady=5)
    Label(q1,text='At the end I would also like to thank my friend Akash for helping me even at the dead of the night.',font='arial 15',bg='light green').pack(padx=10,pady=5)
def z():
    root.destroy()
    t1=Tk()
    t1.geometry('390x650')
    t1.configure(bg='green')
    Label(t1,text='JJJ Production',bd=5,relief='ridge',font='comic 20 bold',bg='light blue').pack(padx=10,pady=5)
    Label(t1,text='Enter the CAR company name :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e=Entry(t1)
    e.pack(padx=10,pady=5)
    Label(t1,text='Enter the model name :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e1=Entry(t1)
    e1.pack(padx=10,pady=5)
    Label(t1,text='Enter the car type :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e2=Entry(t1)
    e2.pack(padx=10,pady=5)
    Label(t1,text='Enter the manufacture year in YYYY :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e3=Entry(t1)
    e3.pack(padx=10,pady=5)
    Label(t1,text='Enter the Chassis number :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e4=Entry(t1)
    e4.pack(padx=10,pady=5)
    Label(t1,text='Enter the Owner Name :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e5=Entry(t1)
    e5.pack(padx=10,pady=5)
    Label(t1,text='Enter the mode of payment :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e6=Entry(t1)
    e6.pack(padx=10,pady=5)
    Label(t1,text='Enter the date of purchase :',relief='ridge',bg='light green').pack(padx=10,pady=5)
    e7=Entry(t1)
    e7.pack(padx=10,pady=5)
    cur.execute("create table if not exists c1(compname varchar(20),modname varchar(20),type varchar(10),year number,cno int(16) primary key,oname varchar(25),mop varchar(10),dop date)")
    def clear():
        e.delete(0,END),e1.delete(0,END),e2.delete(0,END),e3.delete(0,END),e4.delete(0,END),e5.delete(0,END),e6.delete(0,END),e7.delete(0,END)
    def enter():
        A=[e.get(),e1.get(),e2.get(),e3.get(),e4.get(),e5.get(),e6.get(),e7.get()]
        cur.execute("insert into c1 values(?,?,?,?,?,?,?,?)",A)
        con.commit()
        clear()
    def show():
        t=Toplevel(t1)
        t.geometry('1000x500+0+0')
        t.configure(bg='blue')
        sbar=Scrollbar(t,orient=HORIZONTAL)
        sbar.pack(side=BOTTOM,fill=X)
        cur.execute('select * from c1')
        Label(t,text='Cars in your Database :',relief='ridge',bg='GREY').pack(padx=10,pady=5)
        Label(t,text=''+str(cur.fetchall()),bg='light blue').pack(padx=10,pady=5)
    Button(t1,text='Input Details',relief='raised',command=enter).pack(padx=10,pady=5)
    Button(t1,text='Show Details',relief='raised',command=show).pack(padx=10,pady=5)
    def Z():
        t2=Toplevel(t1)
        t2.geometry('250x150')
        t2.configure(bg='light green')
        def regno():
            q2=Tk()
            q2.configure(bg='cyan')
            Label(q2,text='Generate Reg. number',relief='groove',bg='yellow').pack(padx=10,pady=20)
            cur.execute("create table if not exists c2(cno int(16) references c1(cno),regno number(4)primary key)")
            Label(q2,text='Enter Chassi number').pack(padx=10,pady=10)
            e12=Entry(q2)
            e12.pack(padx=10,pady=10)
            def cl():
                e12.delete(0,END)
            def r():
                i=random.randrange(0,9999)
                Label(q2,text='UP 64 AY '+str(i),bg='red').pack(padx=10,pady=10)
                cur.execute("insert into c2 values (?,?)",(e12.get(),i))
                con.commit()
            Button(q2,text='Generate',command=r).pack(padx=10,pady=10)
        def z1():
            t3=Toplevel(t2)
            #t3.geometry('400x125')
            t3.configure(bg='light green')
            Label(t3,text='Enter the Chassis number:',relief='groove',bg='cyan').pack(padx=10,pady=5)
            e8=Entry(t3)
            e8.pack(padx=10,pady=5)
            e8.get()
            def a10():
                cur.execute('select * from c1 where cno=?',(e8.get(),))
                Label(t3,text='The details of the car you searched for :',bg='light blue').pack(padx=10,pady=5)
                Label(t3,text=''+str(cur.fetchall()),bg='light blue').pack(padx=10,pady=5)
            Button(t3,text='GO',command=a10).pack(padx=10,pady=5)
        def z2():
            t4=Toplevel(t2)
            #t4.geometry('400x125')
            t4.configure(bg='light green')
            Label(t4,text='Enter the date :',relief='groove',bg='cyan').pack(padx=10,pady=5)
            e9=Entry(t4)
            e9.pack(padx=10,pady=5)
            e9.get()
            def a11():
                cur.execute('select count(cno) from c1 where dop=?',(e9.get(),))
                Label(t4,text='The number of the cars registered on searched date :',bg='light blue').pack(padx=10,pady=5)
                Label(t3,text=''+str(cur.fetchall()),bg='light blue').pack(padx=10,pady=5)
            Button(t4,text='GO',command=a11).pack(padx=10,pady=5)   
        def z3():
            t5=Toplevel(t2)
            #t5.geometry('400x150')
            t5.configure(bg='light green')
            Label(t5,text='Enter the year (from) :',relief='groove',bg='cyan').pack(padx=10,pady=5)
            e10=Entry(t5)
            e10.pack(padx=10,pady=5)
            e10.get()
            Label(t5,text='Enter the year (to) :',relief='groove',bg='cyan').pack(padx=10,pady=5)        
            e11=Entry(t5)
            e11.pack(padx=10,pady=5)
            e11.get()
            def a12():
                cur.execute('select count(cno) from c1 where dop between ? and ?',(e10.get(),e11.get()))
                Label(t5,text='The number of the cars registered on searched date :',bg='light blue').pack(padx=10,pady=5)
                Label(t5,text=''+str(cur.fetchall()),bg='light blue').pack(padx=10,pady=5)
            Button(t5,text='GO',command=a12).pack(padx=10,pady=5)
        Button(t2,text='Details of perticular car',relief='raised',command=z1).pack(padx=10,pady=5)
        Button(t2,text='Number of cars registered on',relief='raised',command=z2).pack(padx=10,pady=5)
        Button(t2,text='Number of cars registered between',relief='raised',command=z3).pack(padx=10,pady=5)
        Button(t2,text='Generate Registration Number',relief='raised',command=regno).pack(padx=10,pady=5)
    Button(t1,text='Fetch',relief='raised',command=Z).pack(padx=10,pady=5)
Button(root,text='Click to proceed',relief='raised',command=z).pack(padx=10,pady=10)
Button(root,text='About Project',relief='raised',command=zzz).pack(padx=10,pady=10)
Button(root,text='Developers Info',relief='raised',command=zz).pack(padx=10,pady=10)
root.mainloop()
#random_number

